# Generated by Django 5.0.6 on 2024-06-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ["id"], "verbose_name": "раздел", "verbose_name_plural": "разделы"},
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"ordering": ["id"], "verbose_name": "материал", "verbose_name_plural": "материалы"},
        ),
    ]
