# Generated by Django 5.0.6 on 2024-06-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_alter_material_course_question_answer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ["id"], "verbose_name": "ответ", "verbose_name_plural": "ответы"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["id"], "verbose_name": "вопрос", "verbose_name_plural": "вопросы"},
        ),
        migrations.AlterField(
            model_name="chapter",
            name="name",
            field=models.CharField(max_length=150, unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.CharField(max_length=150, unique=True, verbose_name="Вопрос"),
        ),
    ]
