# Generated by Django 5.0.6 on 2024-06-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0006_alter_answer_options_remove_answer_is_correct_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="question",
            name="choices",
        ),
        migrations.RemoveField(
            model_name="question",
            name="material",
        ),
        migrations.RemoveField(
            model_name="question",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="test",
            name="question",
        ),
        migrations.RemoveField(
            model_name="test",
            name="material",
        ),
        migrations.RemoveField(
            model_name="test",
            name="owner",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Test",
        ),
    ]
