# Generated by Django 5.0.6 on 2024-06-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0007_remove_question_answer_remove_question_choices_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="material",
            old_name="course",
            new_name="chapter",
        ),
    ]
